/* Copyright (C) Germán Augusto Sotelo Arévalo - All Rights Reserved
 * Unauthorized copying of this file, via any medium is strictly prohibited
 * Proprietary and confidential
 * Written by Germán Augusto Sotelo Arévalo <gasotelo@crystaltech.co>, December 2018
 */
package jcrystal.configs.server.dbs;

public enum DBType {
	GOOGLE_DATASTORE,
	MYSQL,
	GOOGLE_FIRESTORE,
	GOOGLE_REALTIMEDB,
	GOOGLE_STORAGE,
	GOOGLE_BIG_QUERY;
	public boolean allowsAutogeneratedKeys() {
		switch (this) {
		case MYSQL:
		case GOOGLE_DATASTORE:
		case GOOGLE_FIRESTORE:
			return true;
		default:
			return false;
		}
	}
	
}
